import { useState } from 'react';
import { CheckCircle2, CreditCard, Download, FileText, MapPin, QrCode, ShieldCheck, Star } from 'lucide-react';

import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Separator } from '@/components/ui/separator';

const qrImageToDataUrl = async (url) => {
  const response = await fetch(url);
  if (!response.ok) throw new Error('Unable to load verification QR code.');
  const blob = await response.blob();

  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(reader.result);
    reader.onerror = () => reject(new Error('Unable to read verification QR code.'));
    reader.readAsDataURL(blob);
  });
};

const DigitalPortfolioModal = ({
  isOpen,
  workerName = 'Service Provider',
  serviceType = 'General Service',
  bio = 'Dedicated service professional',
  location = 'Baliwag, Bulacan',
  rating = 4.8,
  profilePhoto,
  gcashNumber = '09XXXXXXXXX',
  onClose,
}) => {
  const [generationError, setGenerationError] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const ratingLabel = Number.isFinite(Number(rating)) ? Number(rating).toFixed(1) : 'Not rated';
  const qrCodeUrl = `https://api.qrserver.com/v1/create-qr-code/?size=240x240&data=${encodeURIComponent(
    `TrabaWho Profile: ${workerName} - ${serviceType}`
  )}`;

  const generatePDF = async () => {
    try {
      setGenerationError('');
      setIsGenerating(true);
      const { jsPDF } = await import('jspdf');
      const doc = new jsPDF('p', 'mm', 'a4');
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 20;
      const contentWidth = pageWidth - (margin * 2);

      doc.setFillColor(21, 87, 192);
      doc.rect(0, 0, pageWidth, 46, 'F');
      doc.setFillColor(255, 255, 255);
      doc.roundedRect(margin, 13, 35, 8, 4, 4, 'F');
      doc.setTextColor(21, 87, 192);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(9);
      doc.text('TRABAWHO', margin + 17.5, 18.4, { align: 'center' });
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(23);
      doc.text('Professional Portfolio', margin, 32);

      let y = 61;
      doc.setTextColor(15, 23, 42);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(20);
      doc.text(doc.splitTextToSize(workerName, contentWidth), margin, y);
      y += 9;
      doc.setTextColor(21, 87, 192);
      doc.setFontSize(12);
      doc.text(doc.splitTextToSize(serviceType, contentWidth), margin, y);
      y += 8;
      doc.setTextColor(71, 85, 105);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(10);
      doc.text(`Verified provider  |  Rating ${ratingLabel} / 5`, margin, y);
      y += 11;

      doc.setDrawColor(226, 232, 240);
      doc.line(margin, y, pageWidth - margin, y);
      y += 11;

      const addSection = (label, value) => {
        doc.setTextColor(21, 87, 192);
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(10);
        doc.text(label.toUpperCase(), margin, y);
        y += 6;
        doc.setTextColor(30, 41, 59);
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(10.5);
        const lines = doc.splitTextToSize(value, contentWidth);
        doc.text(lines, margin, y);
        y += (lines.length * 5.5) + 9;
      };

      addSection('Professional summary', bio);
      addSection('Service location', location);
      addSection('Payment contact', `GCash ${gcashNumber}`);

      doc.setTextColor(21, 87, 192);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.text('PROFILE VERIFICATION', margin, y);
      y += 7;

      try {
        const qrDataUrl = await qrImageToDataUrl(qrCodeUrl);
        doc.addImage(qrDataUrl, 'PNG', margin, y, 42, 42);
      } catch {
        doc.setDrawColor(203, 213, 225);
        doc.roundedRect(margin, y, 42, 42, 2, 2, 'S');
        doc.setTextColor(100, 116, 139);
        doc.setFont('helvetica', 'normal');
        doc.setFontSize(8);
        doc.text('QR unavailable', margin + 21, y + 22, { align: 'center' });
      }

      doc.setTextColor(71, 85, 105);
      doc.setFont('helvetica', 'normal');
      doc.setFontSize(9);
      doc.text('Scan to verify this provider profile on TrabaWho.', margin + 50, y + 17);
      doc.text('Profile details reflect the information available at export.', margin + 50, y + 24);

      doc.setDrawColor(226, 232, 240);
      doc.line(margin, pageHeight - 18, pageWidth - margin, pageHeight - 18);
      doc.setTextColor(100, 116, 139);
      doc.setFontSize(8);
      doc.text('Generated by TrabaWho | Trusted Service Marketplace', margin, pageHeight - 11);
      doc.text(new Date().toLocaleDateString('en-PH'), pageWidth - margin, pageHeight - 11, { align: 'right' });

      const safeName = workerName.replace(/[^a-z0-9]+/gi, '-').replace(/^-|-$/g, '') || 'provider';
      doc.save(`${safeName}-TrabaWho-Portfolio.pdf`);
    } catch (error) {
      setGenerationError(error?.message || 'Could not generate the PDF. Please try again.');
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <Dialog open={isOpen} onOpenChange={(open) => { if (!open) onClose(); }}>
      <DialogContent className="max-w-4xl gap-0 overflow-hidden p-0">
        <DialogHeader className="px-6 pb-5 pt-6">
          <div className="mb-2 flex items-center gap-2 text-primary">
            <FileText className="size-5" aria-hidden="true" />
            <Badge variant="secondary">PDF portfolio</Badge>
          </div>
          <DialogTitle>Preview professional portfolio</DialogTitle>
          <DialogDescription>Review the information below before downloading the shareable PDF.</DialogDescription>
        </DialogHeader>

        <Separator />

        <div className="grid min-h-0 gap-6 overflow-y-auto p-6 lg:grid-cols-[minmax(0,1.5fr)_minmax(15rem,0.75fr)]">
          <article className="rounded-xl bg-muted/45 p-5" aria-label="Portfolio preview">
            <header className="flex min-w-0 items-start gap-4">
              {profilePhoto ? <img className="size-14 shrink-0 rounded-full object-cover ring-1 ring-border" src={profilePhoto} alt="" /> : null}
              <div className="min-w-0 flex-1">
                <h2 className="truncate text-xl font-bold">{workerName}</h2>
                <p className="mt-1 font-semibold text-primary">{serviceType}</p>
                <div className="mt-2 flex flex-wrap items-center gap-2">
                  <Badge variant="success"><ShieldCheck aria-hidden="true" />Verified provider</Badge>
                  <span className="inline-flex items-center gap-1 text-sm text-muted-foreground"><Star className="size-4 fill-orange-400 text-orange-400" aria-hidden="true" />{ratingLabel} / 5</span>
                </div>
              </div>
            </header>

            <Separator className="my-5" />

            <div className="space-y-5">
              <section>
                <h3 className="text-sm font-semibold">Professional summary</h3>
                <p className="mt-1 text-sm leading-6 text-muted-foreground">{bio}</p>
              </section>
              <div className="grid gap-4 sm:grid-cols-2">
                <section className="flex gap-3"><MapPin className="mt-0.5 size-4 shrink-0 text-primary" aria-hidden="true" /><div><h3 className="text-sm font-semibold">Service location</h3><p className="mt-1 text-sm text-muted-foreground">{location}</p></div></section>
                <section className="flex gap-3"><CreditCard className="mt-0.5 size-4 shrink-0 text-primary" aria-hidden="true" /><div><h3 className="text-sm font-semibold">Payment contact</h3><p className="mt-1 text-sm text-muted-foreground">GCash {gcashNumber}</p></div></section>
              </div>
              <section className="flex items-center gap-4 rounded-lg bg-background p-4">
                <img src={qrCodeUrl} alt="Profile verification QR code" className="size-24 shrink-0" />
                <div><QrCode className="mb-2 size-5 text-primary" aria-hidden="true" /><h3 className="text-sm font-semibold">Profile verification</h3><p className="mt-1 text-xs leading-5 text-muted-foreground">Clients can scan this code to verify the provider information.</p></div>
              </section>
            </div>
          </article>

          <aside>
            <h3 className="font-semibold">Ready to share</h3>
            <p className="mt-1 text-sm leading-6 text-muted-foreground">The exported PDF is formatted for email, messaging, and printing.</p>
            <ul className="mt-5 space-y-4 text-sm">
              <li className="flex gap-3"><CheckCircle2 className="mt-0.5 size-4 shrink-0 text-emerald-600" aria-hidden="true" /><span><strong className="block">Clean PDF layout</strong><span className="text-muted-foreground">Uses standard fonts and print-safe formatting.</span></span></li>
              <li className="flex gap-3"><CheckCircle2 className="mt-0.5 size-4 shrink-0 text-emerald-600" aria-hidden="true" /><span><strong className="block">Verification included</strong><span className="text-muted-foreground">The QR code remains embedded in the document.</span></span></li>
              <li className="flex gap-3"><CheckCircle2 className="mt-0.5 size-4 shrink-0 text-emerald-600" aria-hidden="true" /><span><strong className="block">Current profile data</strong><span className="text-muted-foreground">Name, service, location, and bio are taken from your profile.</span></span></li>
            </ul>
            {generationError ? <p className="mt-5 rounded-lg bg-destructive/10 p-3 text-sm font-medium text-destructive" role="alert">{generationError}</p> : null}
          </aside>
        </div>

        <DialogFooter className="px-6 pb-5 pt-4">
          <Button type="button" variant="outline" onClick={onClose}>Cancel</Button>
          <Button type="button" onClick={() => void generatePDF()} isLoading={isGenerating}>
            <Download aria-hidden="true" />{isGenerating ? 'Generating PDF…' : 'Download PDF'}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
};

export default DigitalPortfolioModal;
