import {
  AdminDashboard,
  Dashboard,
  MyBookings,
  MyWork,
  Profile,
  AccountSettings,
  BrowseServicesPage,
  Settings,
  WorkerDashboard,
} from '../index';

// Map each view to its component and required props
export const viewMap = {
  'admin-dashboard': {
    component: AdminDashboard,
    propsBuilder: (context) => ({
      appTheme: context.appTheme,
      currentView: context.currentView,
      onLogout: context.handleLogout,
      onOpenDashboard: context.handleBackToClientDashboard,
      onOpenAdminDashboard: context.handleOpenAdminDashboard,
    }),
  },
  'client-dashboard': {
    component: Dashboard,
    propsBuilder: (context) => ({
      appTheme: context.appTheme,
      currentView: context.currentView,
      searchQuery: context.currentSearchQuery || '',
      onSearchChange: context.handleSearchChange || (() => {}),
      onLogout: context.handleLogout,
      onBecomeSeller: context.handleOpenSellerOnboarding,
      onOpenMyBookings: context.handleOpenMyBookings,
      onOpenChatPage: context.handleOpenChatPage,
      sellerProfile: context.sellerProfile,
      onOpenMyWork: context.handleOpenMyWork,
      onOpenProfile: context.handleOpenProfile,
      onOpenAccountSettings: context.handleOpenAccountSettings,
      onOpenSettings: context.handleOpenSettings,
      onOpenSellerSetup: context.handleOpenSellerOnboarding,
      onOpenDashboard: context.handleBackToClientDashboard,
      onOpenBrowseServices: context.handleOpenBrowseServices,
      onOpenAdminDashboard: context.handleOpenAdminDashboard,
    }),
  },
  'browse-services': {
    component: BrowseServicesPage,
    propsBuilder: (context) => ({
      mode: 'authenticated',
      appTheme: context.appTheme,
      currentView: context.currentView,
      searchQuery: context.currentSearchQuery || '',
      onSearchChange: context.handleSearchChange || (() => {}),
      onLogout: context.handleLogout,
      onOpenSellerSetup: context.handleOpenSellerOnboarding,
      onOpenMyBookings: context.handleOpenMyBookings,
      onOpenChatPage: context.handleOpenChatPage,
      sellerProfile: context.sellerProfile,
      onOpenMyWork: context.handleOpenMyWork,
      onOpenProfile: context.handleOpenProfile,
      onOpenAccountSettings: context.handleOpenAccountSettings,
      onOpenSettings: context.handleOpenSettings,
      onOpenDashboard: context.handleBackToClientDashboard,
      onOpenBrowseServices: context.handleOpenBrowseServices,
      onOpenAdminDashboard: context.handleOpenAdminDashboard,
    }),
  },
  'my-bookings': {
    component: MyBookings,
    propsBuilder: (context) => ({
      appTheme: context.appTheme,
      currentView: context.currentView,
      selectedChatBookingId: context.selectedChatBookingId,
      searchQuery: context.currentSearchQuery || '',
      onSearchChange: context.handleSearchChange || (() => {}),
      onGoHome: context.handleBackToClientDashboard,
      onLogout: context.handleLogout,
      onOpenSellerSetup: context.handleOpenSellerOnboarding,
      onOpenMyWork: context.handleOpenMyWork,
      sellerProfile: context.sellerProfile,
      onOpenProfile: context.handleOpenProfile,
      onOpenAccountSettings: context.handleOpenAccountSettings,
      onOpenSettings: context.handleOpenSettings,
      onOpenMyBookings: context.handleOpenMyBookings,
      onOpenChatPage: context.handleOpenChatPage,
      onOpenDashboard: context.handleBackToClientDashboard,
      onOpenBrowseServices: context.handleOpenBrowseServices,
      onOpenAdminDashboard: context.handleOpenAdminDashboard,
    }),
  },
  'worker-bookings': {
    component: MyBookings,
    propsBuilder: (context) => ({
      appTheme: context.appTheme,
      currentView: context.currentView,
      selectedChatBookingId: context.selectedChatBookingId,
      searchQuery: context.currentSearchQuery || '',
      onSearchChange: context.handleSearchChange || (() => {}),
      onGoHome: context.handleBackToClientDashboard,
      onLogout: context.handleLogout,
      onOpenSellerSetup: context.handleOpenSellerOnboarding,
      onOpenMyWork: context.handleOpenMyWork,
      sellerProfile: context.sellerProfile,
      onOpenProfile: context.handleOpenProfile,
      onOpenAccountSettings: context.handleOpenAccountSettings,
      onOpenSettings: context.handleOpenSettings,
      onOpenMyBookings: context.handleOpenMyBookings,
      onOpenChatPage: context.handleOpenChatPage,
      onOpenDashboard: context.handleBackToClientDashboard,
      onOpenBrowseServices: context.handleOpenBrowseServices,
      onOpenAdminDashboard: context.handleOpenAdminDashboard,
    }),
  },
  chat: {
    component: MyBookings,
    propsBuilder: (context) => ({
      appTheme: context.appTheme,
      currentView: context.currentView,
      selectedChatBookingId: context.selectedChatBookingId,
      searchQuery: context.currentSearchQuery || '',
      onSearchChange: context.handleSearchChange || (() => {}),
      onGoHome: context.handleBackToClientDashboard,
      onLogout: context.handleLogout,
      onOpenSellerSetup: context.handleOpenSellerOnboarding,
      onOpenMyWork: context.handleOpenMyWork,
      sellerProfile: context.sellerProfile,
      onOpenProfile: context.handleOpenProfile,
      onOpenAccountSettings: context.handleOpenAccountSettings,
      onOpenSettings: context.handleOpenSettings,
      onOpenMyBookings: context.handleOpenMyBookings,
      onOpenChatPage: context.handleOpenChatPage,
      onOpenDashboard: context.handleBackToClientDashboard,
      onOpenBrowseServices: context.handleOpenBrowseServices,
      onOpenAdminDashboard: context.handleOpenAdminDashboard,
    }),
  },
  'profile': {
    component: Profile,
    propsBuilder: (context) => ({
      appTheme: context.appTheme,
      currentView: context.currentView,
      searchQuery: context.currentSearchQuery || '',
      onSearchChange: context.handleSearchChange || (() => {}),
      onLogout: context.handleLogout,
      onOpenSellerSetup: context.handleOpenSellerOnboarding,
      onOpenMyBookings: context.handleOpenMyBookings,
      onOpenChatPage: context.handleOpenChatPage,
      sellerProfile: context.sellerProfile,
      onOpenMyWork: context.handleOpenMyWork,
      onOpenProfile: context.handleOpenProfile,
      onOpenAccountSettings: context.handleOpenAccountSettings,
      onOpenSettings: context.handleOpenSettings,
      userLocation: context.userLocation,
      onBackToDashboard: context.handleBackToClientDashboard,
      onUpdateProfile: context.handleProfileUpdate,
      onUpdatePassword: context.handlePasswordUpdate,
      onOpenDashboard: context.handleBackToClientDashboard,
      onOpenBrowseServices: context.handleOpenBrowseServices,
      onOpenAdminDashboard: context.handleOpenAdminDashboard,
    }),
  },
  'account-settings': {
    component: AccountSettings,
    propsBuilder: (context) => ({
      appTheme: context.appTheme,
      currentView: context.currentView,
      searchQuery: context.currentSearchQuery || '',
      onSearchChange: context.handleSearchChange || (() => {}),
      onLogout: context.handleLogout,
      onOpenSellerSetup: context.handleOpenSellerOnboarding,
      onOpenMyBookings: context.handleOpenMyBookings,
      onOpenChatPage: context.handleOpenChatPage,
      sellerProfile: context.sellerProfile,
      onOpenMyWork: context.handleOpenMyWork,
      onOpenProfile: context.handleOpenProfile,
      onOpenAccountSettings: context.handleOpenAccountSettings,
      onOpenSettings: context.handleOpenSettings,
      userLocation: context.userLocation,
      onBackToProfile: context.handleOpenProfile,
      onOpenDashboard: context.handleBackToClientDashboard,
      onOpenBrowseServices: context.handleOpenBrowseServices,
      onUpdateProfile: context.handleProfileUpdate,
      onUpdatePassword: context.handlePasswordUpdate,
      onOpenAdminDashboard: context.handleOpenAdminDashboard,
    }),
  },
  'settings': {
    component: Settings,
    propsBuilder: (context) => ({
      appTheme: context.appTheme,
      currentView: context.currentView,
      searchQuery: context.currentSearchQuery || '',
      onSearchChange: context.handleSearchChange || (() => {}),
      onLogout: context.handleLogout,
      onOpenSellerSetup: context.handleOpenSellerOnboarding,
      onOpenMyBookings: context.handleOpenMyBookings,
      onOpenChatPage: context.handleOpenChatPage,
      sellerProfile: context.sellerProfile,
      onOpenMyWork: context.handleOpenMyWork,
      onOpenProfile: context.handleOpenProfile,
      onOpenAccountSettings: context.handleOpenAccountSettings,
      onOpenSettings: context.handleOpenSettings,
      onBack: context.handleBackFromSettings,
      themeMode: context.themeMode,
      appLanguage: context.appLanguage,
      onThemeChange: context.handleThemeChange,
      onLanguageChange: context.handleLanguageChange,
      onOpenDashboard: context.handleBackToClientDashboard,
      onOpenBrowseServices: context.handleOpenBrowseServices,
      onOpenAdminDashboard: context.handleOpenAdminDashboard,
    }),
  },
  'my-work': {
    component: MyWork,
    propsBuilder: (context) => ({
      appTheme: context.appTheme,
      currentView: context.currentView,
      searchQuery: context.currentSearchQuery || '',
      onSearchChange: context.handleSearchChange || (() => {}),
      onLogout: context.handleLogout,
      onOpenSellerSetup: context.handleOpenSellerOnboarding,
      onOpenMyBookings: context.handleOpenMyBookings,
      onOpenChatPage: context.handleOpenChatPage,
      sellerProfile: context.sellerProfile,
      onOpenMyWork: context.handleOpenMyWork,
      onOpenProfile: context.handleOpenProfile,
      onOpenAccountSettings: context.handleOpenAccountSettings,
      onOpenSettings: context.handleOpenSettings,
      onBackToDashboard: context.handleBackToClientDashboard,
      onAddNewWork: context.handleOpenSellerOnboarding,
      onOpenDashboard: context.handleBackToClientDashboard,
      onOpenBrowseServices: context.handleOpenBrowseServices,
      onOpenAdminDashboard: context.handleOpenAdminDashboard,
    }),
  },
  'worker-dashboard': {
    component: WorkerDashboard,
    propsBuilder: (context) => ({
      appTheme: context.appTheme,
      currentView: context.currentView,
      searchQuery: context.currentSearchQuery || '',
      onSearchChange: context.handleSearchChange || (() => {}),
      onLogout: context.handleLogout,
      onOpenSellerSetup: context.handleOpenSellerOnboarding,
      onOpenMyBookings: () => context.handleOpenMyBookings('incoming'),
      onOpenChatPage: context.handleOpenChatPage,
      sellerProfile: context.sellerProfile,
      onOpenMyWork: context.handleOpenMyWork,
      onOpenProfile: context.handleOpenProfile,
      onOpenAccountSettings: context.handleOpenAccountSettings,
      onOpenSettings: context.handleOpenSettings,
      onBackToClient: context.handleBackToClientDashboard,
      onOpenDashboard: context.handleBackToClientDashboard,
      onOpenBrowseServices: context.handleOpenBrowseServices,
      onOpenAdminDashboard: context.handleOpenAdminDashboard,
    }),
  },
};

/**
 * Renders the correct view based on currentView and application context
 * @param {string} currentView - The current view key
 * @param {object} context - Navigation context with all state and handlers
 * @returns {JSX.Element} The rendered view component or null
 */
export const renderView = (currentView, context) => {
  const viewConfig = viewMap[currentView];

  if (!viewConfig) {
    // Fallback to client-dashboard if view not found
    return renderView('client-dashboard', context);
  }

  const { component: Component, propsBuilder } = viewConfig;
  const props = {
    themeMode: context.themeMode,
    onThemeChange: context.handleThemeChange,
    ...propsBuilder(context),
  };

  return <Component {...props} />;
};
