-- Administrative follow-up records recommendations and evidence requests,
-- never money movement or a final adjudication.
create table public.booking_support_admin_actions (
  id bigint generated by default as identity primary key,
  case_id uuid not null references public.booking_support_cases(id) on delete restrict,
  actor_id uuid not null references auth.users(id),
  action text not null check (action in (
    'request_information', 'rework_arranged', 'reschedule_needed', 'refund_review_needed')),
  target_party text check (target_party in ('client', 'provider', 'both')),
  reason text not null check (length(trim(reason)) >= 20),
  operation_id text not null,
  created_at timestamptz not null default now(),
  unique (case_id, operation_id),
  check ((action = 'request_information' and target_party is not null)
    or (action <> 'request_information' and target_party is null))
);
alter table public.booking_support_admin_actions enable row level security;
create policy booking_support_admin_actions_read on public.booking_support_admin_actions
  for select to authenticated using (public.is_current_user_admin() or exists (
    select 1 from public.booking_support_cases c
    join public.bookings b on b.id = c.booking_id
    where c.id = case_id and (b.buyer_id = auth.uid() or b.seller_id = auth.uid())
  ));
revoke insert, update, delete on public.booking_support_admin_actions from anon, authenticated;
grant select on public.booking_support_admin_actions to authenticated;
create trigger booking_support_admin_actions_immutable
  before update or delete on public.booking_support_admin_actions
  for each row execute function public.prevent_booking_case_action_mutation();

create function public.record_booking_support_followup(
  p_case_id uuid, p_action text, p_target_party text,
  p_reason text, p_operation_id text
) returns public.booking_support_admin_actions
language plpgsql security definer set search_path = public as $$
declare
  v_actor uuid := auth.uid();
  v_case public.booking_support_cases%rowtype;
  v_booking public.bookings%rowtype;
  v_prior public.booking_support_admin_actions%rowtype;
  v_result public.booking_support_admin_actions%rowtype;
  v_reason text := trim(coalesce(p_reason, ''));
begin
  if v_actor is null or not public.is_current_user_admin() then
    raise exception 'Only an administrator may record case follow-up' using errcode = '42501'; end if;
  if nullif(trim(coalesce(p_operation_id, '')), '') is null then
    raise exception 'Operation ID required' using errcode = '22023'; end if;
  if p_action is null or p_action not in (
    'request_information', 'rework_arranged', 'reschedule_needed', 'refund_review_needed') then
    raise exception 'Unsupported support action' using errcode = '22023'; end if;
  if length(v_reason) < 20 then
    raise exception 'Explain the follow-up in at least 20 characters' using errcode = '22023'; end if;
  if (p_action = 'request_information' and (p_target_party is null
    or p_target_party not in ('client', 'provider', 'both')))
    or (p_action <> 'request_information' and p_target_party is not null) then
    raise exception 'Choose a valid party for the information request' using errcode = '22023'; end if;
  select * into v_case from public.booking_support_cases where id = p_case_id for update;
  if not found then raise exception 'Support case not found' using errcode = 'P0002'; end if;
  select * into v_prior from public.booking_support_admin_actions
    where case_id = p_case_id and operation_id = p_operation_id;
  if found then
    if v_prior.actor_id <> v_actor or v_prior.action <> p_action
      or v_prior.target_party is distinct from p_target_party
      or v_prior.reason <> v_reason then
      raise exception 'Operation ID was already used for another action' using errcode = '23505'; end if;
    return v_prior;
  end if;
  if v_case.status = 'closed' then
    raise exception 'A closed case cannot receive follow-up' using errcode = '23514'; end if;
  select * into v_booking from public.bookings where id = v_case.booking_id;
  insert into public.booking_support_admin_actions
    (case_id, actor_id, action, target_party, reason, operation_id)
    values (p_case_id, v_actor, p_action, p_target_party, v_reason, p_operation_id)
    returning * into v_result;
  update public.booking_support_cases set status = 'under_review'
    where id = p_case_id;
  insert into public.booking_audit_events
    (booking_id, event_type, actor_id, actor_role, reason, idempotency_key,
      from_status, to_status, event_data)
    values (v_case.booking_id, 'admin_case_followup', v_actor, 'admin',
      v_reason, p_operation_id, v_booking.status, v_booking.status,
      jsonb_build_object('case_id', p_case_id, 'action', p_action,
        'target_party', p_target_party, 'money_moved', false));
  return v_result;
end;
$$;
revoke all on function public.record_booking_support_followup(uuid, text, text, text, text) from public;
grant execute on function public.record_booking_support_followup(uuid, text, text, text, text) to authenticated;
