-- Secure booking completion lifecycle.
-- Delivery is a seller claim; completion requires buyer confirmation or a
-- service-role auto-confirm job. Payment and dispute state are independent.

alter table public.bookings
  add column if not exists delivery_status text not null default 'not_delivered',
  add column if not exists payment_status text not null default 'unpaid',
  add column if not exists cash_collection_status text not null default 'not_applicable',
  add column if not exists dispute_status text not null default 'none',
  add column if not exists schedule_version integer not null default 1,
  add column if not exists delivered_schedule_version integer,
  add column if not exists delivered_at timestamptz,
  add column if not exists delivered_by uuid references auth.users(id),
  add column if not exists completion_due_at timestamptz,
  add column if not exists completed_at timestamptz,
  add column if not exists completed_by uuid references auth.users(id),
  add column if not exists dispute_opened_at timestamptz,
  add column if not exists dispute_opened_by uuid references auth.users(id),
  add column if not exists dispute_reason text,
  add column if not exists dispute_deadline_at timestamptz;

alter table public.bookings
  drop constraint if exists bookings_delivery_status_check,
  drop constraint if exists bookings_payment_status_check,
  drop constraint if exists bookings_cash_collection_status_check,
  drop constraint if exists bookings_dispute_status_check;

alter table public.bookings
  add constraint bookings_delivery_status_check
    check (delivery_status in ('not_delivered', 'seller_claimed', 'buyer_confirmed')),
  add constraint bookings_payment_status_check
    check (payment_status in ('unpaid', 'pending_provider', 'pending_buyer_acknowledgement', 'paid', 'refunded')),
  add constraint bookings_cash_collection_status_check
    check (cash_collection_status in ('not_applicable', 'awaiting_collection', 'seller_claimed', 'buyer_acknowledged')),
  add constraint bookings_dispute_status_check
    check (dispute_status in ('none', 'open', 'resolved_buyer', 'resolved_seller', 'closed')),
  add constraint bookings_schedule_version_check check (schedule_version > 0);

-- Grandfather existing records without trusting client metadata for new ones.
update public.bookings
set
  delivery_status = case when status = 'completed' then 'buyer_confirmed' else delivery_status end,
  payment_status = case
    when status = 'refunded' then 'refunded'
    when status = 'completed' or payment_reference is not null then 'paid'
    else payment_status
  end,
  cash_collection_status = case
    when coalesce(metadata->>'payment_method', '') = 'after-service-cash' and status = 'completed'
      then 'buyer_acknowledged'
    when coalesce(metadata->>'payment_method', '') = 'after-service-cash'
      then 'awaiting_collection'
    else 'not_applicable'
  end,
  delivered_at = case when status = 'completed' then coalesce(delivered_at, updated_at) else delivered_at end,
  completed_at = case when status = 'completed' then coalesce(completed_at, updated_at) else completed_at end,
  dispute_deadline_at = case
    when status = 'completed' then coalesce(dispute_deadline_at, updated_at + interval '48 hours')
    else dispute_deadline_at
  end;

create table if not exists public.booking_audit_events (
  id bigint generated by default as identity primary key,
  booking_id uuid not null references public.bookings(id) on delete restrict,
  event_type text not null,
  actor_id uuid references auth.users(id),
  actor_role text not null,
  reason text,
  idempotency_key text,
  from_status text,
  to_status text,
  event_data jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists booking_audit_events_booking_created_idx
  on public.booking_audit_events(booking_id, created_at desc);
create unique index if not exists booking_audit_events_idempotency_idx
  on public.booking_audit_events(
    booking_id,
    event_type,
    coalesce(actor_id, '00000000-0000-0000-0000-000000000000'::uuid),
    idempotency_key
  )
  where idempotency_key is not null;

alter table public.booking_audit_events enable row level security;

drop policy if exists booking_audit_events_select_participant on public.booking_audit_events;
create policy booking_audit_events_select_participant
on public.booking_audit_events for select to authenticated
using (
  exists (
    select 1 from public.bookings b
    where b.id = booking_id
      and (b.buyer_id = auth.uid() or b.seller_id = auth.uid())
  )
  or public.is_current_user_admin()
);

create or replace function public.prevent_booking_audit_mutation()
returns trigger language plpgsql set search_path = public as $$
begin
  raise exception 'Booking audit events are append-only' using errcode = '42501';
end;
$$;

drop trigger if exists booking_audit_events_immutable on public.booking_audit_events;
create trigger booking_audit_events_immutable
before update or delete on public.booking_audit_events
for each row execute function public.prevent_booking_audit_mutation();

revoke insert, update, delete on public.booking_audit_events from anon, authenticated;

create or replace function public.protect_booking_workflow_fields()
returns trigger language plpgsql set search_path = public as $$
declare
  v_controlled boolean := coalesce(current_setting('app.booking_workflow_rpc', true), '') = 'on';
begin
  if tg_op = 'UPDATE' and not v_controlled and auth.role() = 'authenticated' then
    if new.delivery_status is distinct from old.delivery_status
      or new.payment_status is distinct from old.payment_status
      or new.cash_collection_status is distinct from old.cash_collection_status
      or new.dispute_status is distinct from old.dispute_status
      or new.delivered_schedule_version is distinct from old.delivered_schedule_version
      or new.delivered_at is distinct from old.delivered_at
      or new.delivered_by is distinct from old.delivered_by
      or new.completion_due_at is distinct from old.completion_due_at
      or new.completed_at is distinct from old.completed_at
      or new.completed_by is distinct from old.completed_by
      or new.dispute_opened_at is distinct from old.dispute_opened_at
      or new.dispute_opened_by is distinct from old.dispute_opened_by
      or new.dispute_reason is distinct from old.dispute_reason
      or new.dispute_deadline_at is distinct from old.dispute_deadline_at
      or new.payment_reference is distinct from old.payment_reference then
      raise exception 'Protected booking fields must be changed through a workflow RPC'
        using errcode = '42501';
    end if;

    if (new.status = 'completed' and old.status <> 'completed')
      or (old.status = 'completed' and new.status not in ('completed', 'refunded')) then
      raise exception 'Completion and reopening must use a workflow RPC'
        using errcode = '42501';
    end if;

    if new.metadata->>'ui_status' in ('Completed Service', 'Service Delivered', 'Refunded')
      and new.metadata->>'ui_status' is distinct from old.metadata->>'ui_status' then
      raise exception 'Terminal UI status is database controlled'
        using errcode = '42501';
    end if;

    if (old.delivery_status <> 'not_delivered' or old.dispute_status = 'open')
      and (
        (new.status is distinct from old.status and not (old.status = 'completed' and new.status = 'refunded'))
        or new.slot_id is distinct from old.slot_id
        or new.start_ts is distinct from old.start_ts
        or new.end_ts is distinct from old.end_ts
      ) then
      raise exception 'Delivered or disputed bookings require a controlled transition'
        using errcode = '42501';
    end if;
  end if;

  if tg_op = 'UPDATE' and (
    new.slot_id is distinct from old.slot_id
    or new.start_ts is distinct from old.start_ts
    or new.end_ts is distinct from old.end_ts
  ) then
    new.schedule_version := old.schedule_version + 1;
  end if;

  return new;
end;
$$;

drop trigger if exists bookings_protect_workflow_fields on public.bookings;
create trigger bookings_protect_workflow_fields
before update on public.bookings
for each row execute function public.protect_booking_workflow_fields();

create or replace function public.validate_review_after_completion()
returns trigger language plpgsql security definer set search_path = public as $$
declare
  v_booking public.bookings%rowtype;
begin
  select * into v_booking from public.bookings where id = new.booking_id;
  if not found or v_booking.status <> 'completed' then
    raise exception 'Ratings are only allowed after booking completion' using errcode = '23514';
  end if;
  if new.reviewer_id <> v_booking.buyer_id or new.seller_id <> v_booking.seller_id then
    raise exception 'Review participants do not match the completed booking' using errcode = '42501';
  end if;
  return new;
end;
$$;

drop trigger if exists reviews_require_completed_booking on public.reviews;
create trigger reviews_require_completed_booking
before insert or update of booking_id, reviewer_id, seller_id on public.reviews
for each row execute function public.validate_review_after_completion();

create or replace function public.mark_booking_delivered(
  p_booking_id uuid,
  p_idempotency_key text
) returns public.bookings
language plpgsql security definer set search_path = public as $$
declare
  v_booking public.bookings%rowtype;
  v_actor uuid := auth.uid();
begin
  if v_actor is null then raise exception 'Authentication required' using errcode = '28000'; end if;
  if nullif(trim(p_idempotency_key), '') is null then raise exception 'Idempotency key required' using errcode = '22023'; end if;

  select * into v_booking from public.bookings where id = p_booking_id for update;
  if not found then raise exception 'Booking not found' using errcode = 'P0002'; end if;
  if v_booking.seller_id <> v_actor then raise exception 'Only the seller can claim delivery' using errcode = '42501'; end if;
  if exists (select 1 from public.booking_audit_events where booking_id = p_booking_id and event_type = 'seller_delivered' and actor_id = v_actor and idempotency_key = p_idempotency_key) then return v_booking; end if;
  if v_booking.status not in ('confirmed', 'in_progress') or v_booking.delivery_status <> 'not_delivered' then
    raise exception 'Booking is not eligible for delivery' using errcode = '23514';
  end if;
  if v_booking.dispute_status = 'open' then raise exception 'Disputed booking cannot be delivered' using errcode = '23514'; end if;

  perform set_config('app.booking_workflow_rpc', 'on', true);
  update public.bookings set
    delivery_status = 'seller_claimed',
    delivered_at = now(),
    delivered_by = v_actor,
    delivered_schedule_version = schedule_version,
    completion_due_at = now() + interval '72 hours',
    metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('ui_status', 'Service Delivered')
  where id = p_booking_id returning * into v_booking;

  insert into public.booking_audit_events(booking_id, event_type, actor_id, actor_role, idempotency_key, from_status, to_status, event_data)
  values (p_booking_id, 'seller_delivered', v_actor, 'seller', p_idempotency_key, v_booking.status, v_booking.status,
    jsonb_build_object('early_delivery', v_booking.end_ts is not null and now() < v_booking.end_ts, 'schedule_version', v_booking.schedule_version));
  return v_booking;
end;
$$;

create or replace function public.confirm_booking_completion(
  p_booking_id uuid,
  p_idempotency_key text
) returns public.bookings
language plpgsql security definer set search_path = public as $$
declare
  v_booking public.bookings%rowtype;
  v_actor uuid := auth.uid();
  v_from_status text;
begin
  if v_actor is null then raise exception 'Authentication required' using errcode = '28000'; end if;
  if nullif(trim(p_idempotency_key), '') is null then raise exception 'Idempotency key required' using errcode = '22023'; end if;
  select * into v_booking from public.bookings where id = p_booking_id for update;
  if not found then raise exception 'Booking not found' using errcode = 'P0002'; end if;
  if v_booking.buyer_id <> v_actor then raise exception 'Only the buyer can confirm completion' using errcode = '42501'; end if;
  if exists (select 1 from public.booking_audit_events where booking_id = p_booking_id and event_type = 'buyer_confirmed_completion' and actor_id = v_actor and idempotency_key = p_idempotency_key) then return v_booking; end if;
  if v_booking.delivery_status <> 'seller_claimed' then raise exception 'Seller has not claimed delivery' using errcode = '23514'; end if;
  if v_booking.delivered_schedule_version <> v_booking.schedule_version then raise exception 'Booking schedule changed after delivery claim' using errcode = '40001'; end if;
  if v_booking.payment_status <> 'paid' then raise exception 'Payment must be confirmed before completion' using errcode = '23514'; end if;
  if v_booking.dispute_status = 'open' then raise exception 'Resolve the dispute before completion' using errcode = '23514'; end if;

  v_from_status := v_booking.status;
  perform set_config('app.booking_workflow_rpc', 'on', true);
  update public.bookings set
    status = 'completed', delivery_status = 'buyer_confirmed', completed_at = now(), completed_by = v_actor,
    dispute_deadline_at = now() + interval '48 hours',
    metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('ui_status', 'Completed Service', 'can_rate', true)
  where id = p_booking_id returning * into v_booking;
  insert into public.booking_audit_events(booking_id, event_type, actor_id, actor_role, idempotency_key, from_status, to_status)
  values (p_booking_id, 'buyer_confirmed_completion', v_actor, 'buyer', p_idempotency_key, v_from_status, 'completed');
  return v_booking;
end;
$$;

create or replace function public.claim_cash_payment_collected(
  p_booking_id uuid,
  p_amount numeric,
  p_idempotency_key text
) returns public.bookings
language plpgsql security definer set search_path = public as $$
declare v_booking public.bookings%rowtype; v_actor uuid := auth.uid();
begin
  if v_actor is null then raise exception 'Authentication required' using errcode = '28000'; end if;
  if nullif(trim(p_idempotency_key), '') is null then raise exception 'Idempotency key required' using errcode = '22023'; end if;
  select * into v_booking from public.bookings where id = p_booking_id for update;
  if not found then raise exception 'Booking not found' using errcode = 'P0002'; end if;
  if v_booking.seller_id <> v_actor then raise exception 'Only the seller can claim cash collection' using errcode = '42501'; end if;
  if coalesce(v_booking.metadata->>'payment_method', '') <> 'after-service-cash' then raise exception 'Booking is not a cash payment' using errcode = '23514'; end if;
  if round(coalesce(p_amount, -1), 2) <> v_booking.total_charged_amount then raise exception 'Cash amount must equal booking total' using errcode = '23514'; end if;
  if exists (select 1 from public.booking_audit_events where booking_id = p_booking_id and event_type = 'seller_claimed_cash' and actor_id = v_actor and idempotency_key = p_idempotency_key) then return v_booking; end if;
  perform set_config('app.booking_workflow_rpc', 'on', true);
  update public.bookings set payment_status = 'pending_buyer_acknowledgement', cash_collection_status = 'seller_claimed'
  where id = p_booking_id returning * into v_booking;
  insert into public.booking_audit_events(booking_id, event_type, actor_id, actor_role, idempotency_key, from_status, to_status, event_data)
  values (p_booking_id, 'seller_claimed_cash', v_actor, 'seller', p_idempotency_key, v_booking.status, v_booking.status, jsonb_build_object('amount', p_amount));
  return v_booking;
end;
$$;

create or replace function public.acknowledge_cash_payment(
  p_booking_id uuid,
  p_idempotency_key text
) returns public.bookings
language plpgsql security definer set search_path = public as $$
declare v_booking public.bookings%rowtype; v_actor uuid := auth.uid();
begin
  if v_actor is null then raise exception 'Authentication required' using errcode = '28000'; end if;
  if nullif(trim(p_idempotency_key), '') is null then raise exception 'Idempotency key required' using errcode = '22023'; end if;
  select * into v_booking from public.bookings where id = p_booking_id for update;
  if not found then raise exception 'Booking not found' using errcode = 'P0002'; end if;
  if v_booking.buyer_id <> v_actor then raise exception 'Only the buyer can acknowledge cash payment' using errcode = '42501'; end if;
  if v_booking.cash_collection_status <> 'seller_claimed' then raise exception 'Seller has not claimed cash collection' using errcode = '23514'; end if;
  if exists (select 1 from public.booking_audit_events where booking_id = p_booking_id and event_type = 'buyer_acknowledged_cash' and actor_id = v_actor and idempotency_key = p_idempotency_key) then return v_booking; end if;
  perform set_config('app.booking_workflow_rpc', 'on', true);
  update public.bookings set payment_status = 'paid', cash_collection_status = 'buyer_acknowledged'
  where id = p_booking_id returning * into v_booking;
  insert into public.booking_audit_events(booking_id, event_type, actor_id, actor_role, idempotency_key, from_status, to_status)
  values (p_booking_id, 'buyer_acknowledged_cash', v_actor, 'buyer', p_idempotency_key, v_booking.status, v_booking.status);
  return v_booking;
end;
$$;

create or replace function public.record_booking_online_payment(
  p_booking_id uuid,
  p_external_reference text,
  p_amount numeric,
  p_idempotency_key text
) returns public.bookings
language plpgsql security definer set search_path = public as $$
declare v_booking public.bookings%rowtype;
begin
  if auth.role() <> 'service_role' then raise exception 'Only the payment server can confirm online payment' using errcode = '42501'; end if;
  if nullif(trim(p_external_reference), '') is null or nullif(trim(p_idempotency_key), '') is null then raise exception 'Payment reference and idempotency key required' using errcode = '22023'; end if;
  select * into v_booking from public.bookings where id = p_booking_id for update;
  if not found then raise exception 'Booking not found' using errcode = 'P0002'; end if;
  if round(coalesce(p_amount, -1), 2) <> v_booking.total_charged_amount then raise exception 'Provider amount does not match booking total' using errcode = '23514'; end if;
  if exists (select 1 from public.booking_audit_events where booking_id = p_booking_id and event_type = 'provider_payment_confirmed' and idempotency_key = p_idempotency_key) then return v_booking; end if;
  perform set_config('app.booking_workflow_rpc', 'on', true);
  update public.bookings set payment_status = 'paid', payment_reference = p_external_reference
  where id = p_booking_id returning * into v_booking;
  insert into public.booking_audit_events(booking_id, event_type, actor_role, idempotency_key, from_status, to_status, event_data)
  values (p_booking_id, 'provider_payment_confirmed', 'payment_server', p_idempotency_key, v_booking.status, v_booking.status, jsonb_build_object('amount', p_amount, 'reference', p_external_reference));
  return v_booking;
end;
$$;

create or replace function public.open_booking_dispute(
  p_booking_id uuid,
  p_reason text,
  p_idempotency_key text
) returns public.bookings
language plpgsql security definer set search_path = public as $$
declare v_booking public.bookings%rowtype; v_actor uuid := auth.uid(); v_role text;
begin
  if v_actor is null then raise exception 'Authentication required' using errcode = '28000'; end if;
  if length(trim(coalesce(p_reason, ''))) < 10 then raise exception 'Dispute reason must be at least 10 characters' using errcode = '22023'; end if;
  if nullif(trim(p_idempotency_key), '') is null then raise exception 'Idempotency key required' using errcode = '22023'; end if;
  select * into v_booking from public.bookings where id = p_booking_id for update;
  if not found then raise exception 'Booking not found' using errcode = 'P0002'; end if;
  if v_actor not in (v_booking.buyer_id, v_booking.seller_id) then raise exception 'Only booking participants can dispute' using errcode = '42501'; end if;
  v_role := case when v_actor = v_booking.buyer_id then 'buyer' else 'seller' end;
  if v_booking.status = 'completed' and (v_booking.dispute_deadline_at is null or now() > v_booking.dispute_deadline_at) then raise exception 'Dispute window has closed' using errcode = '23514'; end if;
  if v_booking.status in ('cancelled', 'refunded') then raise exception 'Booking cannot be disputed in its current state' using errcode = '23514'; end if;
  if exists (select 1 from public.booking_audit_events where booking_id = p_booking_id and event_type = 'dispute_opened' and actor_id = v_actor and idempotency_key = p_idempotency_key) then return v_booking; end if;
  perform set_config('app.booking_workflow_rpc', 'on', true);
  update public.bookings set dispute_status = 'open', dispute_opened_at = now(), dispute_opened_by = v_actor, dispute_reason = trim(p_reason)
  where id = p_booking_id returning * into v_booking;
  insert into public.booking_audit_events(booking_id, event_type, actor_id, actor_role, reason, idempotency_key, from_status, to_status)
  values (p_booking_id, 'dispute_opened', v_actor, v_role, trim(p_reason), p_idempotency_key, v_booking.status, v_booking.status);
  return v_booking;
end;
$$;

create or replace function public.auto_confirm_delivered_bookings()
returns integer language plpgsql security definer set search_path = public as $$
declare v_booking public.bookings%rowtype; v_count integer := 0;
begin
  if auth.role() <> 'service_role' then raise exception 'Only the booking scheduler can auto-confirm' using errcode = '42501'; end if;
  for v_booking in
    select * from public.bookings
    where delivery_status = 'seller_claimed' and payment_status = 'paid' and dispute_status <> 'open'
      and completion_due_at <= now() and delivered_schedule_version = schedule_version
      and status in ('confirmed', 'in_progress')
    for update skip locked
  loop
    perform set_config('app.booking_workflow_rpc', 'on', true);
    update public.bookings set status = 'completed', delivery_status = 'buyer_confirmed', completed_at = now(), completed_by = null,
      dispute_deadline_at = now() + interval '48 hours',
      metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('ui_status', 'Completed Service', 'can_rate', true)
    where id = v_booking.id;
    insert into public.booking_audit_events(booking_id, event_type, actor_role, idempotency_key, from_status, to_status)
    values (v_booking.id, 'auto_confirmed_completion', 'system', 'auto-' || v_booking.delivered_schedule_version, v_booking.status, 'completed')
    on conflict do nothing;
    v_count := v_count + 1;
  end loop;
  return v_count;
end;
$$;

create or replace function public.admin_override_booking_status(
  p_booking_id uuid,
  p_action text,
  p_reason text,
  p_idempotency_key text
) returns public.bookings
language plpgsql security definer set search_path = public as $$
declare v_booking public.bookings%rowtype; v_actor uuid := auth.uid(); v_from_status text;
begin
  if v_actor is null or not public.is_current_user_admin() then raise exception 'Administrator access required' using errcode = '42501'; end if;
  if p_action not in ('complete', 'reopen') then raise exception 'Admin action must be complete or reopen' using errcode = '22023'; end if;
  if length(trim(coalesce(p_reason, ''))) < 10 or nullif(trim(p_idempotency_key), '') is null then raise exception 'Reason and idempotency key required' using errcode = '22023'; end if;
  select * into v_booking from public.bookings where id = p_booking_id for update;
  if not found then raise exception 'Booking not found' using errcode = 'P0002'; end if;
  if exists (select 1 from public.booking_audit_events where booking_id = p_booking_id and event_type = 'admin_' || p_action and actor_id = v_actor and idempotency_key = p_idempotency_key) then return v_booking; end if;
  v_from_status := v_booking.status;
  perform set_config('app.booking_workflow_rpc', 'on', true);
  if p_action = 'complete' then
    update public.bookings set status = 'completed', delivery_status = 'buyer_confirmed', completed_at = now(), completed_by = v_actor,
      dispute_deadline_at = now() + interval '48 hours', dispute_status = case when dispute_status = 'open' then 'closed' else dispute_status end,
      metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('ui_status', 'Completed Service', 'can_rate', true)
    where id = p_booking_id returning * into v_booking;
  else
    update public.bookings set status = 'confirmed', delivery_status = 'not_delivered', delivered_at = null, delivered_by = null,
      delivered_schedule_version = null, completion_due_at = null, completed_at = null, completed_by = null, dispute_deadline_at = null,
      metadata = coalesce(metadata, '{}'::jsonb) || jsonb_build_object('ui_status', 'Service Scheduled', 'can_rate', false)
    where id = p_booking_id returning * into v_booking;
  end if;
  insert into public.booking_audit_events(booking_id, event_type, actor_id, actor_role, reason, idempotency_key, from_status, to_status)
  values (p_booking_id, 'admin_' || p_action, v_actor, 'admin', trim(p_reason), p_idempotency_key, v_from_status, v_booking.status);
  return v_booking;
end;
$$;

revoke all on function public.mark_booking_delivered(uuid, text) from public;
revoke all on function public.confirm_booking_completion(uuid, text) from public;
revoke all on function public.claim_cash_payment_collected(uuid, numeric, text) from public;
revoke all on function public.acknowledge_cash_payment(uuid, text) from public;
revoke all on function public.record_booking_online_payment(uuid, text, numeric, text) from public;
revoke all on function public.open_booking_dispute(uuid, text, text) from public;
revoke all on function public.auto_confirm_delivered_bookings() from public;
revoke all on function public.admin_override_booking_status(uuid, text, text, text) from public;

grant execute on function public.mark_booking_delivered(uuid, text) to authenticated;
grant execute on function public.confirm_booking_completion(uuid, text) to authenticated;
grant execute on function public.claim_cash_payment_collected(uuid, numeric, text) to authenticated;
grant execute on function public.acknowledge_cash_payment(uuid, text) to authenticated;
grant execute on function public.open_booking_dispute(uuid, text, text) to authenticated;
grant execute on function public.admin_override_booking_status(uuid, text, text, text) to authenticated;
grant execute on function public.record_booking_online_payment(uuid, text, numeric, text) to service_role;
grant execute on function public.auto_confirm_delivered_bookings() to service_role;

comment on column public.bookings.delivery_status is 'Seller delivery claim and buyer confirmation state; independent of booking status.';
comment on column public.bookings.payment_status is 'Authoritative payment state. Online paid status is service-role controlled.';
comment on table public.booking_audit_events is 'Immutable, append-only lifecycle audit trail with idempotency protection.';
